language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql
install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
script: phpunit --configuration $DB.phpunit.xml
notifications:
     email: "me@leonardorifeli.com"
