language: php
php:
    - 5.6

before_script:
  - cp app/config/parameters-sample.yml app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console cache:clear --env=test
  - php app/console cache:clear --env=test

script:
  - phpunit -c app

notifications:
  email:
    - me@leonardorifeli.com
    - leonardorifeli@gmail.com
