sign-in:
    path:     /sign-in
    defaults: { _controller: LoginBundle:SignIn:index }

sign-up:
    resource: "@LoginBundle/Resources/config/routing/sign-up.yml"
    prefix:   /sign-up

login_check:
    pattern: /login-check

login_logout:
    pattern: /logout

login_verify:
    path:     /verify-redirect
    defaults: { _controller: LoginBundle:Security:verify }
