bank:
    path:     /
    defaults: { _controller: BankBundle:Bank:index }

bank_new:
    path:     /new
    defaults: { _controller: BankBundle:Bank:new }

bank_create:
    path:     /create
    defaults: { _controller: BankBundle:Bank:create }
    methods:  [POST]

bank_edit:
    path:     /{id}/edit
    defaults: { _controller: BankBundle:Bank:edit }

bank_update:
    path:     /{id}/update
    defaults: { _controller: BankBundle:Bank:update }
    methods:  [PUT]

bank_delete:
    path:     /{id}/delete
    defaults: { _controller: BankBundle:Bank:delete }
    methods:  [DELETE]
