user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

management:
    resource: "@ManagementBundle/Resources/config/routing.yml"
    prefix:   /

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /system
