management:
    resource: "@ManagementBundle/Resources/config/routing.yml"
    prefix:   /management

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /system
