automatic_manager:
    resource: "@AutomaticManagerBundle/Resources/config/routing.yml"
    prefix:   /

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

card:
    resource: "@CardBundle/Resources/config/routing.yml"
    prefix:   /card

business:
    resource: "@BusinessBundle/Resources/config/routing.yml"
    prefix:   /

bank:
    resource: "@BankBundle/Resources/config/routing.yml"
    prefix:   /bank

theme:
    resource: "@ThemeBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
