security:
    encoders:
            System\Bundle\SystemBundle\Entity\User:
                algorithm:        sha512
                encode_as_base64: true
                iterations:       1

    role_hierarchy:
            ROLE_USER: [ROLE_ADMIN, ROLE_USER, ROLE_CUSTOMER]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_CUSTOMER, ROLE_USER] }
    access_denied_url: /
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login-check
            logout:
                path:   /logout
                target: /

    providers:
         main:
            entity: { class: SystemBundle:User }
