security:
    encoders:
            Morfeu\Bundle\EntityBundle\Entity\User:
                algorithm:        sha512
                encode_as_base64: true
                iterations:       1

    role_hierarchy:
            ROLE_USER: [ROLE_ADMIN, ROLE_USER]

    access_control:
        - { path: ^/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER] }
    access_denied_url: /sign-in
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path:  /sign-in
                check_path:  /login-check
            logout:
                path:   /logout
                target: /

    providers:
         main:
            entity: { class: EntityBundle:User }
