services:

    bank.service:
        class: Morfeu\Bundle\BusinessBundle\Service\BankService
        arguments: [@doctrine.orm.entity_manager]

    bankUser.service:
        class: Morfeu\Bundle\BusinessBundle\Service\BankUserService
        arguments: [@doctrine.orm.entity_manager]

    card.service:
        class: Morfeu\Bundle\BusinessBundle\Service\CardService
        arguments: [@doctrine.orm.entity_manager]

    payment.service:
        class: Morfeu\Bundle\BusinessBundle\Service\PaymentService
        arguments: [@doctrine.orm.entity_manager]

    userProfile.service:
        class: Morfeu\Bundle\BusinessBundle\Service\UserProfileService
        arguments: [@doctrine.orm.entity_manager]

    user.service:
        class: Morfeu\Bundle\BusinessBundle\Service\UserService
        arguments: [@doctrine.orm.entity_manager]

    dashboard.service:
        class: Morfeu\Bundle\BusinessBundle\Service\DashboardService
        arguments: [@user.service, @payment.service, @card.service, @bankUser.service]

    connectImapMail.service:
        class: Morfeu\Bundle\BusinessBundle\Service\ConnectImapMailService
        arguments: []

    mailImportInformation.service:
        class: Morfeu\Bundle\BusinessBundle\Service\MailImportInformationService
        arguments: [@connectImapMail.service]

    typePaymentExtension.twig:
        class: Morfeu\Bundle\BusinessBundle\Twig\TypePaymentExtension
        tags:
          - { name: twig.extension }
