<?php

namespace DoctrineProxy\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BreedAnimal extends \App\Entity\BreedAnimal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'animalType', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'name', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'productFinder', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'postage', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'hair', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'activeCrm', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'obs');
        }

        return array('__isInitialized__', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'animalType', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'name', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'productFinder', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'postage', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'hair', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'activeCrm', '' . "\0" . 'App\\Entity\\BreedAnimal' . "\0" . 'obs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BreedAnimal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnimalType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnimalType', array());

        return parent::getAnimalType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnimalType($animalType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnimalType', array($animalType));

        return parent::setAnimalType($animalType);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductFinder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductFinder', array());

        return parent::getProductFinder();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductFinder($productFinder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductFinder', array($productFinder));

        return parent::setProductFinder($productFinder);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostage', array());

        return parent::getPostage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostage($postage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostage', array($postage));

        return parent::setPostage($postage);
    }

    /**
     * {@inheritDoc}
     */
    public function getHair()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHair', array());

        return parent::getHair();
    }

    /**
     * {@inheritDoc}
     */
    public function setHair($hair)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHair', array($hair));

        return parent::setHair($hair);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveCrm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveCrm', array());

        return parent::getActiveCrm();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveCrm($activeCrm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveCrm', array($activeCrm));

        return parent::setActiveCrm($activeCrm);
    }

    /**
     * {@inheritDoc}
     */
    public function getObs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObs', array());

        return parent::getObs();
    }

    /**
     * {@inheritDoc}
     */
    public function setObs($obs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObs', array($obs));

        return parent::setObs($obs);
    }

}
