<?php

namespace DoctrineProxy\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserProfile extends \App\Entity\UserProfile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'user', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'profile', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'cpf', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'name', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'surname', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'address', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'complement', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'district', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'city', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'state', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'number', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'phoneHome', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'phoneComercial', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'cellphone', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'mobileOperator', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'blogOrSite', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'howFindUs', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'howFindUsOther', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'dateUpdate');
        }

        return array('__isInitialized__', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'user', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'profile', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'cpf', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'name', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'surname', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'address', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'complement', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'district', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'city', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'state', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'number', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'phoneHome', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'phoneComercial', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'cellphone', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'mobileOperator', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'blogOrSite', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'howFindUs', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'howFindUsOther', '' . "\0" . 'App\\Entity\\UserProfile' . "\0" . 'dateUpdate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserProfile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', array());

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile($profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', array($profile));

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', array());

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', array($cpf));

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', array());

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', array($surname));

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', array());

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', array($genre));

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplement', array());

        return parent::getComplement();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplement($complement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplement', array($complement));

        return parent::setComplement($complement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistrict', array());

        return parent::getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistrict($district)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistrict', array($district));

        return parent::setDistrict($district);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', array());

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', array($zipCode));

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneHome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneHome', array());

        return parent::getPhoneHome();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneHome($phoneHome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneHome', array($phoneHome));

        return parent::setPhoneHome($phoneHome);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneComercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneComercial', array());

        return parent::getPhoneComercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneComercial($phoneComercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneComercial', array($phoneComercial));

        return parent::setPhoneComercial($phoneComercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getCellphone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCellphone', array());

        return parent::getCellphone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCellphone($cellphone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCellphone', array($cellphone));

        return parent::setCellphone($cellphone);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileOperator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileOperator', array());

        return parent::getMobileOperator();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileOperator($mobileOperator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileOperator', array($mobileOperator));

        return parent::setMobileOperator($mobileOperator);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlogOrSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlogOrSite', array());

        return parent::getBlogOrSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlogOrSite($blogOrSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlogOrSite', array($blogOrSite));

        return parent::setBlogOrSite($blogOrSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getHowFindUs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHowFindUs', array());

        return parent::getHowFindUs();
    }

    /**
     * {@inheritDoc}
     */
    public function setHowFindUs($howFindUs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHowFindUs', array($howFindUs));

        return parent::setHowFindUs($howFindUs);
    }

    /**
     * {@inheritDoc}
     */
    public function getHowFindUsOther()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHowFindUsOther', array());

        return parent::getHowFindUsOther();
    }

    /**
     * {@inheritDoc}
     */
    public function setHowFindUsOther($howFindUsOther)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHowFindUsOther', array($howFindUsOther));

        return parent::setHowFindUsOther($howFindUsOther);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdate', array());

        return parent::getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdate($dateUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdate', array($dateUpdate));

        return parent::setDateUpdate($dateUpdate);
    }

}
