routes:
    login:
        pattern:  /login
        controller: Morfeu\Controller\SignInController::indexAction
        requirements:
            _method:  GET

    logout:
        pattern:  /logout
        controller: Morfeu\Controller\SignInController::indexAction
        requirements:
            _method:  GET

    login_check:
        pattern:  /login_check
        controller: Morfeu\Controller\SignInController::indexAction
        requirements:
            _method:  GET

    dashboard:
        pattern:  /
        controller: Morfeu\Controller\DashboardController::indexAction
        requirements:
            _method:  GET

    bank_list:
        pattern:  /bank
        controller: Morfeu\Controller\BankController::indexAction
        requirements:
            _method:  GET

    bank_new:
        pattern:  /bank/new
        controller: Morfeu\Controller\BankController::newAction
        requirements:
            _method:  GET

    bank_create:
        pattern:  /bank/new
        controller: Morfeu\Controller\BankController::createAction
        requirements:
            _method:  POST
