payment:
    path:     /
    defaults: { _controller: PaymentBundle:Payment:index }

payment_new:
    path:     /new
    defaults: { _controller: PaymentBundle:Payment:new }

payment_edit:
    path:     /{id}/edit
    defaults: { _controller: PaymentBundle:Payment:edit }

payment_delete:
    path:     /{id}/{typePayment}/delete
    defaults: { _controller: PaymentBundle:Payment:delete }

payment_detail:
    path:     /{id}/detail
    defaults: { _controller: PaymentBundle:Payment:detail }

payment_update:
    path:     /{id}/update
    defaults: { _controller: PaymentBundle:Payment:update }
    methods:  [PUT]

payment_create:
    path:     /create
    defaults: { _controller: PaymentBundle:Payment:create }
    methods:  [POST]

payment_accomplished:
    path:     /accomplished
    defaults: { _controller: PaymentBundle:Accomplished:index }

payment_accomplished_filter:
    path:     /accomplished/filter
    defaults: { _controller: PaymentBundle:Accomplished:filter }
    methods:  [GET]

payment_received:
    path:     /received
    defaults: { _controller: PaymentBundle:Received:index }

payment_received_filter:
    path:     /accomplished/filter
    defaults: { _controller: PaymentBundle:Accomplished:filter }
    methods:  [GET]
