card:
    path:     /
    defaults: { _controller: CardBundle:Card:index }

card_new:
    path:     /new
    defaults: { _controller: CardBundle:Card:new }

card_create:
    path:     /create
    defaults: { _controller: CardBundle:Card:create }
    methods:  [POST]

card_edit:
    path:     /{id}/edit
    defaults: { _controller: CardBundle:Card:edit }

card_update:
    path:     /{id}/update
    defaults: { _controller: CardBundle:Card:update }
    methods:  [PUT]

card_delete:
    path:     /{id}/delete
    defaults: { _controller: CardBundle:Card:delete }
    methods:  [DELETE]
